### ISSUE TITLE
salty-coffee doesn't work on Android devices

### ISSUE THREAD

**Issue by kaibaaqua** [NeilMadden/salty-coffee#26]
I want to use salt-coffe `1.0.5` for android apps, but unfortunately, it doesn't work because Android doesn't have either of 
`"NativePRNGNonBlocking", "NativePRNG", "DRBG"` algorithm for `SecureRandom`.

Android uses `SHA1PRNG` (provider is  `AndroidOpenSSL version 1.0`)

It is possible to use `SHA1PRNG` for Android as well?

**Comment by NeilMadden** [comment]
According to [this blog](https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html) from the Android developers, `SHA1PRNG` is deprecated and insecure. It looks like the recommended replacement is `OpenSSLRandom` - can you confirm please?

**Comment by NeilMadden** [comment]
PR merged, many thanks for fixing this. I'll push a new release shortly.

**Comment by NeilMadden** [comment]
Pushed release 1.1.0 resolving this issue. Should be available on Maven Central in the next few hours.
